from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from administrator.models import Administrator
from employees.models import Employee
from rest_framework_simplejwt.tokens import RefreshToken
from datetime import date


class EmployeeCreateTestCase(APITestCase):
    """Test case class for employee creation functionality"""
    
    def setUp(self):
        """
        Set up method that runs before each test.
        Creates an authenticated admin user and prepares test data.
        """
        
        # Create an authenticated administrator user (staff member)
        self.admin_user = Administrator.objects.create_user(
            username='admin1',
            email='admin1@example.com',
            password='AdminPass123.',
            id_administrator='ADM001',
            phone_number=3001234567,
            is_staff=True  # Mark as staff to have admin privileges
        )

        # Generate JWT token for the administrator
        # This simulates a logged-in admin user
        refresh = RefreshToken.for_user(self.admin_user)
        self.access_token = str(refresh.access_token)

        # Store the endpoint URL for employee operations
        # 'employee-list' is the name generated by Django REST Framework's DefaultRouter
        self.url = reverse('employee-list')

        # Prepare employee data that will be used to create a new employee
        self.employee_data = {
            "id_employee": "EMP001",           # Unique employee identifier
            "phone_number": 3009876543,         # Contact phone number
            "name": "Juan",                     # First name
            "lastname": "Pérez",                # Last name
            "document_id": 1234567890,          # National ID or document number
            "role": "Operario",                 # Job role/position
            "contract_date": str(date.today()), # Contract start date (today)
            "state": "active"                   # Employment status
        }

    def test_authenticated_admin_can_create_employee(self):
        """
        Test that verifies an authenticated admin user can successfully 
        create a new employee record.
        """
        
        # Set the authorization header with the JWT access token
        # This authenticates the request as coming from the admin user
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.access_token}')
        
        # Send POST request to create a new employee
        response = self.client.post(self.url, self.employee_data, format='json')

        # Optional debugging: print the response data to console
        print(response.data)

        # Assert that the response status code is 201 CREATED
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

        # Verify that the employee was actually created in the database
        # by checking if an employee with the given ID exists
        self.assertTrue(Employee.objects.filter(id_employee="EMP001").exists())

    def test_unauthenticated_user_cannot_create_employee(self):
        """
        Test that verifies an unauthenticated user CANNOT create employees.
        This ensures the endpoint is properly protected.
        """
        
        # Send POST request WITHOUT authentication credentials
        # No credentials are set, so this simulates an anonymous user
        response = self.client.post(self.url, self.employee_data, format='json')

        # Assert that the request is rejected with 401 UNAUTHORIZED status
        # This confirms that authentication is required
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)